#!/usr/bin/env bash
# configuring a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo service haproxy start

echo 'frontend theproxy
        bind *:80
        default_backend my_backend_servers

backend my_backend_servers
        balance roundrobin
        server 280305-web-01 34.232.65.167
        server 280305-web-02 54.90.27.89' | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy reload
