#!/usr/bin/env bash
#This script dispaly statements using while, if, elif and else loop
x=1
while [ $x -le 10 ]
do
	echo "Best School"
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((x++))
done
